# Generated by Django 6.0.1 on 2026-01-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FamiliarDelEvaluado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres y Apellidos')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=10, verbose_name='Sexo')),
                ('estado_civil', models.CharField(blank=True, max_length=50, verbose_name='Estado Civil')),
                ('nivel_educativo', models.CharField(blank=True, max_length=50, verbose_name='Nivel Educativo')),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='Ocupación/Estudios')),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingresos Mensuales')),
            ],
        ),
        migrations.CreateModel(
            name='FichaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FichaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Aplicación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombres_evaluado', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos_evaluado', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('dni_evaluado', models.CharField(max_length=8, verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('edad_evaluado', models.IntegerField(verbose_name='Edad')),
                ('sexo_evaluado', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, verbose_name='Sexo')),
                ('nivel_educativo', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Universidad', 'Universidad')], default='Secundaria', max_length=20, verbose_name='Nivel Educativo')),
                ('grado_seccion', models.CharField(blank=True, help_text='Ej: 5to A (Solo Primaria/Secundaria)', max_length=50, verbose_name='Grado y Sección')),
                ('carrera_semestre', models.CharField(blank=True, help_text='Ej: Ingeniería - 5to Ciclo (Solo Universidad)', max_length=100, verbose_name='Carrera y Semestre')),
                ('direccion_domicilio', models.CharField(max_length=200, verbose_name='Dirección Actual')),
                ('distrito', models.CharField(max_length=100, verbose_name='Distrito')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('lugar_origen', models.CharField(max_length=100, verbose_name='Lugar de Origen')),
                ('telefono_contacto', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('emergencia_nombres', models.CharField(max_length=150, verbose_name='Nombre Emergencia')),
                ('emergencia_telefono', models.CharField(max_length=20, verbose_name='Teléfono Emergencia')),
                ('emergencia_parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('jefe_hogar', models.CharField(max_length=150, verbose_name='Jefe de Hogar')),
                ('num_integrantes', models.IntegerField(verbose_name='Número de Integrantes')),
                ('observaciones_familia', models.TextField(blank=True, verbose_name='Observaciones Familiares')),
                ('puntaje_total', models.IntegerField(default=0)),
                ('nivel_riesgo', models.CharField(blank=True, max_length=50)),
                ('conclusion', models.TextField(blank=True, verbose_name='Conclusión Diagnóstica')),
                ('plan_intervencion', models.TextField(blank=True, verbose_name='Plan de Intervención Recomendado')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_modular', models.CharField(max_length=20, unique=True, verbose_name='Código Modular')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre / Descripción')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('nombre_contacto', models.CharField(max_length=150, verbose_name='Nombre del Contacto')),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200, verbose_name='Alternativa')),
                ('puntaje', models.IntegerField(default=0, verbose_name='Puntaje')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Pregunta')),
                ('orden', models.PositiveIntegerField()),
            ],
        ),
    ]
