# Generated by Django 6.0.1 on 2026-01-28 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fichas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaevaluacion',
            name='usuario_registra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Encuestador'),
        ),
        migrations.AddField(
            model_name='fichadetalle',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='fichas.fichaevaluacion'),
        ),
        migrations.AddField(
            model_name='familiardelevaluado',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='fichas.fichaevaluacion'),
        ),
        migrations.AddField(
            model_name='fichaevaluacion',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fichas.institucion', verbose_name='Institución Evaluada'),
        ),
        migrations.AddField(
            model_name='fichadetalle',
            name='opcion_seleccionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fichas.opcion'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='fichas.dimension'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='fichas.pregunta'),
        ),
        migrations.AddField(
            model_name='fichadetalle',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fichas.pregunta'),
        ),
    ]
