# Generated by Django 6.0.1 on 2026-01-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaevaluacion',
            name='puntaje_dimension_a',
            field=models.IntegerField(default=0, verbose_name='A. Socioeconómicas'),
        ),
        migrations.AddField(
            model_name='fichaevaluacion',
            name='puntaje_dimension_b',
            field=models.IntegerField(default=0, verbose_name='B. Estructura Familiar'),
        ),
        migrations.AddField(
            model_name='fichaevaluacion',
            name='puntaje_dimension_c',
            field=models.IntegerField(default=0, verbose_name='C. Indicadores Educativos'),
        ),
        migrations.AddField(
            model_name='fichaevaluacion',
            name='puntaje_dimension_d',
            field=models.IntegerField(default=0, verbose_name='D. Psicosociales'),
        ),
        migrations.AddField(
            model_name='fichaevaluacion',
            name='puntaje_dimension_e',
            field=models.IntegerField(default=0, verbose_name='E. Acceso Servicios'),
        ),
        migrations.AddField(
            model_name='fichaevaluacion',
            name='puntaje_dimension_f',
            field=models.IntegerField(default=0, verbose_name='F. Factores Protectores'),
        ),
    ]
