# Generated by Django 6.0.1 on 2026-01-30 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_fichaevaluacion_puntaje_dimension_a_and_more'),
        ('ubigeo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaevaluacion',
            name='carrera_semestre',
        ),
        migrations.RemoveField(
            model_name='fichaevaluacion',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='fichaevaluacion',
            name='grado_seccion',
        ),
        migrations.RemoveField(
            model_name='fichaevaluacion',
            name='lugar_origen',
        ),
        migrations.RemoveField(
            model_name='fichaevaluacion',
            name='provincia',
        ),
        migrations.AddField(
            model_name='fichaevaluacion',
            name='ubigeo_departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_dep', to='ubigeo.departamento'),
        ),
        migrations.AddField(
            model_name='fichaevaluacion',
            name='ubigeo_distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_dist', to='ubigeo.distrito'),
        ),
        migrations.AddField(
            model_name='fichaevaluacion',
            name='ubigeo_provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_prov', to='ubigeo.provincia'),
        ),
    ]
