# Generated by Django 6.0.2 on 2026-02-06 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0004_remove_fichaevaluacion_carrera_semestre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_edicion', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(default='Edición de datos', max_length=255)),
                ('detalles', models.TextField(blank=True, help_text='Ej: Cambió el nivel de riesgo de Bajo a Alto')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='fichas.fichaevaluacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_edicion'],
            },
        ),
    ]
