# Generated by Django 6.0.2 on 2026-02-07 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0005_fichahistorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaevaluacion',
            name='usuario_registra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Agente_de_campo'),
        ),
    ]
