# Generated by Django 6.0.1 on 2026-01-30 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Provincia')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='ubigeo.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Distrito')),
                ('region_natural', models.CharField(blank=True, max_length=50, null=True, verbose_name='Región Natural')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='ubigeo.provincia')),
            ],
        ),
    ]
