# Generated by Django 6.0.2 on 2026-02-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('ENCUESTADOR', 'Agente de campo / Alumno')], default='ENCUESTADOR', max_length=20),
        ),
    ]
