# Generated by Django 6.0.2 on 2026-02-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ciclo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cip'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('ENCUESTADOR', 'Profesional')], default='ENCUESTADOR', max_length=20),
        ),
    ]
